const LIVE_STREAMS = Object.freeze([
  {
    id: "bloomberg",
    name: "Bloomberg",
    region: "Global",
    provider: "youtube",
    mode: "embed",
    channelId: "UCIALMKvObZNtJ6AmdCLP7Lg",
    handle: "@markets",
    fallbackUrl: "https://www.youtube.com/@markets/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UCIALMKvObZNtJ6AmdCLP7Lg",
    priority: "critical",
    enabled: true
  },
  {
    id: "reuters",
    name: "Reuters",
    region: "Global",
    provider: "youtube",
    mode: "embed",
    channelId: "UChqUTb7kYRX8-EiaN3XFrSQ",
    handle: "@Reuters",
    fallbackUrl: "https://www.youtube.com/@Reuters/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UChqUTb7kYRX8-EiaN3XFrSQ",
    priority: "normal",
    enabled: true
  },
  {
    id: "bbc-news",
    name: "BBC News",
    region: "Global",
    provider: "youtube",
    mode: "external",
    channelId: null,
    handle: "@BBCNews",
    fallbackUrl: "https://www.youtube.com/@BBCNews/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    priority: "normal",
    enabled: true
  },
  {
    id: "sky-news",
    name: "Sky News",
    region: "Europe",
    provider: "youtube",
    mode: "embed",
    channelId: "UCoMdktPbSTixAyNGwb-UYkQ",
    handle: "@SkyNews",
    fallbackUrl: "https://www.youtube.com/@SkyNews/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UCoMdktPbSTixAyNGwb-UYkQ",
    priority: "critical",
    enabled: true
  },
  {
    id: "france24",
    name: "France 24",
    region: "Europe",
    provider: "youtube",
    mode: "embed",
    channelId: "UCE9-RvWlHixPLyGQk9TRj3Q",
    handle: "@FRANCE24",
    fallbackUrl: "https://www.youtube.com/@FRANCE24/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UCE9-RvWlHixPLyGQk9TRj3Q",
    priority: "normal",
    enabled: true
  },
  {
    id: "dw",
    name: "DW News",
    region: "Europe",
    provider: "youtube",
    mode: "embed",
    channelId: "UCknLrEdhRCp1aegoMqRaCZg",
    handle: "@dwnews",
    fallbackUrl: "https://www.youtube.com/@dwnews/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UCknLrEdhRCp1aegoMqRaCZg",
    priority: "normal",
    enabled: true
  },
  {
    id: "al-jazeera",
    name: "Al Jazeera English",
    region: "MENA",
    provider: "youtube",
    mode: "embed",
    channelId: "UCR0DUmNzPhLyX6wnmvvEgKA",
    handle: "@aljazeeraenglish",
    fallbackUrl: "https://www.youtube.com/@aljazeeraenglish/streams",
    manualVideoId: null,
    lastKnownVideoId: "gCNeDWCI0vo",
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UCR0DUmNzPhLyX6wnmvvEgKA",
    priority: "critical",
    enabled: true
  },
  {
    id: "i24",
    name: "i24NEWS",
    region: "MENA",
    provider: "youtube",
    mode: "external",
    channelId: null,
    handle: "@i24NEWS",
    fallbackUrl: "https://www.youtube.com/@i24NEWS/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    priority: "normal",
    enabled: true
  },
  {
    id: "abc-news",
    name: "ABC News",
    region: "Americas",
    provider: "youtube",
    mode: "embed",
    channelId: "UCBi2mrWuNuyYy4gbM6fU18Q",
    handle: "@ABCNews",
    fallbackUrl: "https://www.youtube.com/@ABCNews/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UCBi2mrWuNuyYy4gbM6fU18Q",
    priority: "normal",
    enabled: true
  },
  {
    id: "cbs-news",
    name: "CBS News",
    region: "Americas",
    provider: "youtube",
    mode: "embed",
    channelId: "UC8p1vwvWtl6T73JiExfWs1g",
    handle: "@CBSNews",
    fallbackUrl: "https://www.youtube.com/@CBSNews/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UC8p1vwvWtl6T73JiExfWs1g",
    priority: "normal",
    enabled: true
  },
  {
    id: "nbc-news",
    name: "NBC News",
    region: "Americas",
    provider: "youtube",
    mode: "embed",
    channelId: "UCeY0bbntWzzVIaj2z3QigXg",
    handle: "@NBCNews",
    fallbackUrl: "https://www.youtube.com/@NBCNews/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UCeY0bbntWzzVIaj2z3QigXg",
    priority: "normal",
    enabled: true
  },
  {
    id: "cbc-news",
    name: "CBC News",
    region: "Americas",
    provider: "youtube",
    mode: "external",
    channelId: null,
    handle: "@CBCNews",
    fallbackUrl: "https://www.youtube.com/@CBCNews/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    priority: "lazy",
    enabled: true
  },
  {
    id: "euronews",
    name: "Euronews",
    region: "Europe",
    provider: "youtube",
    mode: "embed",
    channelId: "UCSrZ3UV4jOidv8ppoVuvW9Q",
    handle: "@euronews",
    fallbackUrl: "https://www.youtube.com/@euronews/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    staticEmbedUrl: "https://www.youtube.com/embed/live_stream?channel=UCSrZ3UV4jOidv8ppoVuvW9Q",
    priority: "normal",
    enabled: true
  },
  {
    id: "ndtv",
    name: "NDTV",
    region: "Asia",
    provider: "youtube",
    mode: "external",
    channelId: null,
    handle: "@NDTV",
    fallbackUrl: "https://www.youtube.com/@NDTV/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    priority: "lazy",
    enabled: true
  },
  {
    id: "wion",
    name: "WION",
    region: "Asia",
    provider: "youtube",
    mode: "external",
    channelId: null,
    handle: "@WION",
    fallbackUrl: "https://www.youtube.com/@WION/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    priority: "lazy",
    enabled: true
  },
  {
    id: "cna",
    name: "CNA",
    region: "Asia",
    provider: "youtube",
    mode: "external",
    channelId: null,
    handle: "@ChannelNewsAsia",
    fallbackUrl: "https://www.youtube.com/@ChannelNewsAsia/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    priority: "lazy",
    enabled: true
  },
  {
    id: "africa-news",
    name: "Africanews",
    region: "Africa",
    provider: "youtube",
    mode: "external",
    channelId: null,
    handle: "@africanews",
    fallbackUrl: "https://www.youtube.com/@africanews/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    priority: "lazy",
    enabled: true
  },
  {
    id: "sky-aus",
    name: "Sky News Australia",
    region: "Oceania",
    provider: "youtube",
    mode: "external",
    channelId: null,
    handle: "@SkyNewsAustralia",
    fallbackUrl: "https://www.youtube.com/@SkyNewsAustralia/streams",
    manualVideoId: null,
    lastKnownVideoId: null,
    priority: "lazy",
    enabled: true
  }
]);

export function buildLiveStreamCatalog() {
  return structuredClone(LIVE_STREAMS);
}

export { LIVE_STREAMS };
