import { Router } from "express";
import { getScenarios, getSignalsDelta, refreshScenarios, deleteScenario, acknowledgeSignals, recoverSignals, getEventImpact, getResearchSources, getCompanyFacts, getEtfHoldings, runResearchSources, acknowledgeAlerts, getCapabilities, getDiagnostics, getPortfolioContext } from "../controllers/researchController.js";
const router = Router();
router.get("/research/scenarios",getScenarios);
router.get("/signals/delta",getSignalsDelta);
router.post("/research/scenarios/refresh",refreshScenarios);
router.post("/research/scenarios/delete",deleteScenario);
router.post("/signals/checkpoint",acknowledgeSignals);
router.post("/signals/recover",recoverSignals);
router.get("/research/event-impact",getEventImpact);
router.get("/research/sources",getResearchSources);
router.get("/research/companyfacts",getCompanyFacts);
router.get("/etf/holdings",getEtfHoldings);
router.post("/research/sources/run",runResearchSources);
router.get("/capabilities", getCapabilities);
router.get("/diagnostics", getDiagnostics);
router.get("/portfolio/context", getPortfolioContext);
router.post("/portfolio/alerts/ack", acknowledgeAlerts);
export default router;
