import { AppError } from "../../utils/error.js";
import { stableHash } from "../../utils/stableHash.js";
import { getInstrumentById } from "../market/instrumentRegistry.js";
import { calculateTechnicalIndicators } from "../market/technicalIndicators.js";
import { resolveExpectedClosedDailyCandle } from "../market/dailyCandleService.js";
const finite=x=>typeof x==="number"&&Number.isFinite(x);
const iso=x=>typeof x==="string"&&Number.isFinite(Date.parse(x));
const priceKey=c=>stableHash({openTime:c.openTime,closeTime:c.closeTime,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume,currency:c.currency,source:c.source,adjusted:c.adjusted});
function usable(c){return c&&!c.synthetic&&!c.provenance?.synthetic&&!['synthetic','fallback','seeded','stale'].includes(c.dataMode)&&[c.open,c.high,c.low,c.close].every(x=>finite(x)&&x>0);}
export function purgedWalkForward(rows,{trainSize=30,testSize=10}={}) {
 const ordered=[...rows].sort((a,b)=>a.issuedAt.localeCompare(b.issuedAt));const folds=[];
 for(let i=trainSize;i<ordered.length;i+=testSize){const test=ordered.slice(i,i+testSize);const start=Date.parse(test[0].issuedAt);const candidates=ordered.slice(Math.max(0,i-trainSize),i);const train=candidates.filter(r=>Date.parse(r.outcomeAt||r.expiresAt)<start&&Date.parse(r.outcomeAvailableAt||r.expiresAt)<=start);folds.push({trainIds:train.map(r=>r.forecastId),testIds:test.map(r=>r.forecastId),purged:candidates.length-train.length,testFrom:test[0].issuedAt,testTo:test.at(-1).issuedAt});}return folds;
}
export class ForecastEvaluationService {
 constructor({store,candleStore,now=Date.now}={}){Object.assign(this,{store,candleStore,now});}
 bars(id){return this.candleStore.query({instrumentId:id,interval:"1day",adjustmentMode:"splits",limit:10000});}
 record(input){if(!/^[A-Za-z0-9._:-]{1,128}$/.test(input.forecastId||"")||["__proto__","constructor","prototype"].includes(input.forecastId)||typeof input.modelVersion!=="string"||!input.modelVersion.trim())throw new AppError("Identificador o modelo inválido.",400,"INVALID_FORECAST");const existing=this.store.state.forecasts[input.forecastId];if(existing){if(existing.requestHash!==stableHash(input))throw new AppError("ID reutilizado con otro pronóstico.",409,"IDEMPOTENCY_CONFLICT");return structuredClone(existing);}
   const now=this.now(),recordedAt=new Date(now).toISOString(),issuedAt=input.issuedAt||recordedAt;
   if(!iso(issuedAt)||Date.parse(issuedAt)>now||Date.parse(issuedAt)<now-60000)throw new AppError("No se admite registrar pronósticos retrospectivos.",400,"FORECAST_BACKDATING_FORBIDDEN");
   const instrument=getInstrumentById(input.instrumentId),benchmark=input.benchmarkInstrumentId?getInstrumentById(input.benchmarkInstrumentId):null;
   if(!instrument||input.benchmarkInstrumentId&&!benchmark)throw new AppError("Identidad no verificada.",400,"UNRESOLVED_INSTRUMENT");
   if(!["return","relative-return","direction"].includes(input.target)||!Number.isInteger(input.horizonHours)||input.horizonHours<1||input.horizonHours>720||input.target==="relative-return"&&!benchmark)throw new AppError("Objetivo u horizonte inválido.",400,"INVALID_FORECAST");
   if(input.target==="direction"?!["up","down","flat"].includes(input.direction):!finite(input.predictedValue))throw new AppError("Pronóstico sin valor comparable.",400,"INVALID_FORECAST");
   if(input.probability!=null&&(input.target!=="direction"||!finite(input.probability)||input.probability<0||input.probability>1||!input.probabilityModelVersion))throw new AppError("Probabilidad exige modelo explícito; confidence heurístico no es válido.",400,"INVALID_PROBABILITY");
   if((input.evidence||[]).some(e=>!iso(e.availableAt)||Date.parse(e.availableAt)>Date.parse(issuedAt)))throw new AppError("Evidencia no disponible al pronosticar.",400,"FUTURE_INFORMATION");
   const before=this.bars(instrument.instrumentId).filter(c=>usable(c)&&Date.parse(c.closeTime)<=Date.parse(issuedAt)&&iso(c.fetchedAt)&&Date.parse(c.fetchedAt)<=Date.parse(issuedAt));const origin=before.at(-1);
   if(!origin)throw new AppError("Faltan precios con disponibilidad histórica conocida.",409,"FORECAST_DATA_UNAVAILABLE");
   const expected=resolveExpectedClosedDailyCandle(instrument,new Date(issuedAt));if(!expected||Date.parse(origin.closeTime)<Date.parse(expected.closeTime))throw new AppError("El precio de origen está desactualizado o su sesión es indeterminada.",409,"FORECAST_DATA_UNAVAILABLE");
   const technical=calculateTechnicalIndicators(before.slice(-500),{interval:"1day",instrument,calculatedAt:issuedAt});if(technical.quality.reason||technical.quality.gapDetected)throw new AppError("Serie incompatible o con huecos.",409,"FORECAST_DATA_UNAVAILABLE");
   let benchmarkOrigin=null;if(benchmark){benchmarkOrigin=this.bars(benchmark.instrumentId).find(c=>c.closeTime===origin.closeTime&&usable(c)&&iso(c.fetchedAt)&&Date.parse(c.fetchedAt)<=Date.parse(issuedAt));if(!benchmarkOrigin||benchmarkOrigin.currency!==origin.currency||benchmarkOrigin.source!==origin.source||benchmarkOrigin.adjusted!==origin.adjusted)throw new AppError("Benchmark no alineado o incompatible; no se convierte FX.",409,"FORECAST_DATA_UNAVAILABLE");}
   const fingerprint=stableHash({instrumentId:input.instrumentId,benchmarkInstrumentId:input.benchmarkInstrumentId||null,target:input.target,horizonHours:input.horizonHours,issuedAt,eventId:input.eventId||null,modelVersion:input.modelVersion});
   if(Object.values(this.store.state.forecasts).some(row=>row.fingerprint===fingerprint))throw new AppError("Pronóstico duplicado.",409,"FORECAST_DUPLICATE");
   if(input.costs&&!(["commissionBps","spreadBps","slippageBps"].every(k=>finite(input.costs[k])&&input.costs[k]>=0&&input.costs[k]<=1000)))throw new AppError("Costes inválidos.",400,"INVALID_FORECAST");
   const row={...input,forecastId:input.forecastId,fingerprint,requestHash:stableHash(input),issuedAt,recordedAt,expiresAt:new Date(Date.parse(issuedAt)+input.horizonHours*3600000).toISOString(),originCandle:structuredClone(origin),originRevision:priceKey(origin),benchmarkOrigin:structuredClone(benchmarkOrigin),featureSeriesRevision:stableHash(before),featureAvailableAt:before.map(c=>c.fetchedAt).sort().at(-1),methodVersion:"forecast-registry-v1",probability:input.probability??null,probabilityMeaning:input.probability==null?null:"P(absolute return > 0)",probabilityKind:input.probability==null?null:"operator-supplied-model-probability; not calibrated by registration",costs:input.costs||null,status:"registered-before-outcome",quality:{synthetic:false,entryBasis:"last-available-daily-close; executable entry price unavailable"}};
   return this.store.transact(state=>state.forecasts[row.forecastId]=row);
 }
 outcome(row,asOf){if(Date.parse(row.expiresAt)>asOf)return {status:"pending-outcome"};
   const bars=this.bars(row.instrumentId);const currentOrigin=bars.find(c=>c.openTime===row.originCandle.openTime);
   if(!currentOrigin||priceKey(currentOrigin)!==row.originRevision)return {status:"data-revision-review-required"};
   const after=bars.find(c=>usable(c)&&Date.parse(c.closeTime)>=Date.parse(row.expiresAt)&&Date.parse(c.closeTime)<=asOf&&iso(c.fetchedAt)&&Date.parse(c.fetchedAt)<=asOf);
   if(!after)return {status:"outcome-data-unavailable"};
   if(after.currency!==row.originCandle.currency||after.source!==row.originCandle.source||after.adjusted!==row.originCandle.adjusted)return {status:"incompatible-outcome"};
   const absoluteReturn=after.close/row.originCandle.close-1;let benchmarkReturn=null;
   if(row.benchmarkInstrumentId){const currentPeerOrigin=this.bars(row.benchmarkInstrumentId).find(c=>c.openTime===row.benchmarkOrigin.openTime);if(!currentPeerOrigin||priceKey(currentPeerOrigin)!==priceKey(row.benchmarkOrigin))return {status:"data-revision-review-required"};const peer=this.bars(row.benchmarkInstrumentId).find(c=>c.closeTime===after.closeTime&&usable(c)&&iso(c.fetchedAt)&&Date.parse(c.fetchedAt)<=asOf);if(!peer||peer.source!==row.benchmarkOrigin.source||peer.currency!==row.benchmarkOrigin.currency||peer.adjusted!==row.benchmarkOrigin.adjusted)return {status:"benchmark-outcome-unavailable"};benchmarkReturn=peer.close/row.benchmarkOrigin.close-1;}
   const observed=row.target==="relative-return"?absoluteReturn-benchmarkReturn:absoluteReturn;
   const direction=observed>0?"up":observed<0?"down":"flat";const expected=row.target==="direction"?row.direction:row.predictedValue>0?"up":row.predictedValue<0?"down":"flat";
   const roundTripCosts=row.costs?(2*row.costs.commissionBps+row.costs.spreadBps+2*row.costs.slippageBps)/10000:null;
   return {status:"observed",outcomeAt:after.closeTime,outcomeAvailableAt:after.fetchedAt,outcomeRevision:priceKey(after),absoluteReturn,benchmarkReturn,observed,netReturn:roundTripCosts==null?null:observed-roundTripCosts,costReason:roundTripCosts==null?"cost-spread-slippage-not-specified":null,correct:expected===direction,falsePositive:expected!=="flat"&&expected!==direction,absoluteError:row.target!=="direction"?Math.abs(row.predictedValue-observed):null,brier:row.probability==null?null:(row.probability-(direction==="up"?1:0))**2};
 }
 evaluate({instrumentIds=[],modelVersion,minSamples=30,limit=100,asOf=new Date(this.now()).toISOString()}={}) {
   if(!iso(asOf)||Date.parse(asOf)>this.now())throw new AppError("Evaluación futura no permitida.",400,"FUTURE_INFORMATION");
   const registered=Object.values(this.store.state.forecasts).filter(r=>(!instrumentIds.length||instrumentIds.includes(r.instrumentId))&&(!modelVersion||r.modelVersion===modelVersion)&&Date.parse(r.recordedAt)<=Date.parse(asOf)).sort((a,b)=>a.issuedAt.localeCompare(b.issuedAt));
   const rows=registered.slice(-1000).map(r=>({forecastId:r.forecastId,instrumentId:r.instrumentId,eventId:r.eventId||null,target:r.target,issuedAt:r.issuedAt,expiresAt:r.expiresAt,modelVersion:r.modelVersion,probability:r.probability,...this.outcome(r,Date.parse(asOf))}));const observed=rows.filter(r=>r.status==="observed");const count=observed.length;const average=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
   const probabilistic=observed.filter(r=>r.brier!=null);const byEvent={};for(const row of observed.filter(r=>r.eventId)){byEvent[row.eventId]??={sampleSize:0,correct:0};byEvent[row.eventId].sampleSize++;byEvent[row.eventId].correct+=Number(row.correct);}
   const bins=Array.from({length:5},(_,i)=>{const values=probabilistic.filter(r=>r.probability>=i/5&&(r.probability<(i+1)/5||i===4));return {from:i/5,to:(i+1)/5,sampleSize:values.length,meanProbability:average(values.map(r=>r.probability)),observedUpFrequency:average(values.map(r=>r.absoluteReturn>0?1:0))};});
   const folds=purgedWalkForward(observed);return {status:count<minSamples?"insufficient-evaluation":"descriptive-evaluation-only",methodVersion:"forecast-evaluation-v1",asOf,snapshotId:stableHash({revision:this.store.state.revision,rows,asOf}),sampleSize:count,minimumSamples:minSamples,coverage:{registered:registered.length,considered:rows.length,partial:registered.length>1000,outcomeCoverage:rows.length?count/rows.length:0,pending:rows.filter(r=>r.status==="pending-outcome").length,excluded:rows.filter(r=>!["observed","pending-outcome"].includes(r.status)).length},
     metrics:{precision:average(observed.map(r=>Number(r.correct))),falsePositives:observed.filter(r=>r.falsePositive).length,duplicates:0,duplicatePolicy:"rejected-at-registration; rejected attempts not retained",meanObservedRelativeReturn:average(observed.filter(r=>r.benchmarkReturn!=null).map(r=>r.absoluteReturn-r.benchmarkReturn)),meanNetReturn:average(observed.filter(r=>r.netReturn!=null).map(r=>r.netReturn)),mae:average(observed.filter(r=>r.absoluteError!=null).map(r=>r.absoluteError)),brier:average(probabilistic.map(r=>r.brier)),brierReason:probabilistic.length?null:"no-real-probabilistic-forecasts",byEvent},
     calibration:probabilistic.length>=minSamples?bins:null,calibrationReason:probabilistic.length<minSamples?"insufficient-probabilistic-evaluation":null,walkForward:{method:"chronological-fixed-window-with-overlapping-horizon-purge-v1",trainSize:30,testSize:10,folds:folds.slice(-20),trainedModel:false},comparators:{zeroReturnMAE:average(observed.map(r=>Math.abs(r.observed))),alwaysUpPrecision:average(observed.map(r=>Number(r.absoluteReturn>0))),benchmarkReturnMAE:average(observed.filter(r=>r.target==="return"&&r.benchmarkReturn!=null).map(r=>Math.abs(r.benchmarkReturn-r.absoluteReturn)))},results:rows.slice(-limit),hasMore:rows.length>limit,
     warnings:["Descriptive evaluation is not evidence of profitability or a completed prospective pilot.","Daily-close proxy entry and first closed outcome after horizon; no executable quotes or FX conversion.","Feature availability is captured at registration; corrected origins require review.","Brier and calibration require actual registered probabilities; heuristic confidence is excluded."]};
 }
}
