import { candleIntervalMs } from "./canonicalCandle.js";

export const NEWS_PRICE_COUPLING_V2 = "news-price-coupling-v2";
export const DEFAULT_COUPLING_PARAMETERS = Object.freeze({ interval: "15min", preEventWindowMin: 60, postEventWindowsMin: [60, 240], adjustmentMode: "splits", relativeVolumeLookback: 20 });

const iso = (value) => { const date = new Date(value); return Number.isFinite(date.getTime()) ? date.toISOString() : null; };
const localParts = (date, timeZone) => Object.fromEntries(new Intl.DateTimeFormat("en-US", { timeZone, hour12: false, weekday: "short", hour: "2-digit", minute: "2-digit" }).formatToParts(date).map((part) => [part.type, part.value]));
const returnOf = (before, after) => Number.isFinite(before) && Number.isFinite(after) && before !== 0 ? after / before - 1 : null;

export function resolveEventMarketSession(instrument, timestamp) {
  if (instrument.sessionPolicy === "24x7") return "24x7";
  const parts = localParts(new Date(timestamp), instrument.timezone); if (!["Mon", "Tue", "Wed", "Thu", "Fri"].includes(parts.weekday)) return "market-closed";
  const minutes = Number(parts.hour) % 24 * 60 + Number(parts.minute); if (minutes < 570) return "premarket"; if (minutes < 960) return "session"; return "after-hours";
}

function compatibleSeries(candles, instrument, interval, adjustmentMode) { return candles.filter((candle) => candle.instrumentId === instrument.instrumentId && candle.interval === interval && candle.currency === instrument.currency && (candle.provenance?.adjustmentMode || (candle.adjusted ? "splits" : "none")) === adjustmentMode).sort((a, b) => Date.parse(a.openTime) - Date.parse(b.openTime)); }
function detectGap(candles, interval) { const expected = candleIntervalMs(interval); if (!expected) return true; return candles.some((candle, index) => { if (!index) return false; const previous = candles[index - 1]; const delta = Date.parse(candle.openTime) - Date.parse(previous.openTime); const sameDay = candle.openTime.slice(0, 10) === previous.openTime.slice(0, 10); return interval === "1day" ? delta > expected * 4 : sameDay && delta > expected * 1.5; }); }
function selectPrices(candles, availableAtMs, preWindowMs, postWindowMs, asOfMs) {
  const before = candles.filter((candle) => Date.parse(candle.closeTime) <= availableAtMs && Date.parse(candle.closeTime) >= availableAtMs - preWindowMs).at(-1) || null;
  const eligibleAfter = candles.filter((candle) => Date.parse(candle.openTime) >= availableAtMs && Date.parse(candle.closeTime) <= Math.min(asOfMs, availableAtMs + postWindowMs)); return { before, after: eligibleAfter.at(-1) || null, eligibleAfter };
}
function relativeVolume(candles, before, after, lookback) { if (!after || !Number.isFinite(Number(after.volume))) return null; const beforeIndex = candles.indexOf(before); const sample = candles.slice(Math.max(0, beforeIndex - lookback + 1), beforeIndex + 1).map((candle) => Number(candle.volume)).filter(Number.isFinite); if (!sample.length) return null; const average = sample.reduce((sum, value) => sum + value, 0) / sample.length; return average > 0 ? Number(after.volume) / average : null; }
function confidence({ coverage, confounded, gap, stale }) { let score = coverage; if (confounded) score -= 0.25; if (gap) score -= 0.25; if (stale) score -= 0.25; return { method: "deterministic-data-coverage-v1", level: score >= 0.8 ? "higher" : score >= 0.5 ? "limited" : "insufficient", calibratedProbability: false }; }
function provenance(news, before, after, benchmarkBefore, benchmarkAfter) { return { news: { provider: news.provider || null, sourceName: news.sourceName || null, dataMode: news.dataMode || null }, price: { source: after?.source || before?.source || null, dataMode: after?.dataMode || before?.dataMode || null, fetchedAt: after?.fetchedAt || before?.fetchedAt || null, methodVersion: after?.methodVersion || before?.methodVersion || null }, benchmark: benchmarkAfter || benchmarkBefore ? { source: benchmarkAfter?.source || benchmarkBefore?.source || null, dataMode: benchmarkAfter?.dataMode || benchmarkBefore?.dataMode || null } : null }; }

/** Pure event-study calculation. It never loads data or calls providers. */
export function calculateNewsPriceCouplingV2({ news, instrument, candles = [], benchmarkInstrument = null, benchmarkCandles = [], competingNews = [], parameters = {}, asOf = new Date().toISOString() } = {}) {
  const params = { ...DEFAULT_COUPLING_PARAMETERS, ...parameters }; const publishedAt = iso(news?.publishedAt); const receivedAt = iso(news?.receivedAt || news?.publishedAt); const asOfIso = iso(asOf); const limitations = ["Movimiento asociado temporalmente; correlación, no causalidad."];
  if (!publishedAt || !receivedAt || !asOfIso || !instrument?.instrumentId) return { methodVersion: NEWS_PRICE_COUPLING_V2, newsId: news?.id || null, instrumentId: instrument?.instrumentId || null, dataQuality: "invalid-input", limitations: [...limitations, "Timestamps or instrument are invalid."] };
  const availableAtMs = Math.max(Date.parse(publishedAt), Date.parse(receivedAt)); const asOfMs = Date.parse(asOfIso); const series = compatibleSeries(candles, instrument, params.interval, params.adjustmentMode).filter((candle) => Date.parse(candle.closeTime) <= asOfMs); const gap = detectGap(series, params.interval); const stale = series.some((candle) => candle.dataMode === "stale" || candle.quality === "stale-if-error"); const maxWindow = Math.max(...params.postEventWindowsMin); const competitors = competingNews.filter((candidate) => candidate.id !== news.id && Math.abs(Math.max(Date.parse(candidate.publishedAt || 0), Date.parse(candidate.receivedAt || candidate.publishedAt || 0)) - availableAtMs) <= maxWindow * 60_000).map((candidate) => candidate.id); const confounded = competitors.length > 0;
  if (instrument.sessionPolicy !== "24x7") limitations.push("Session alignment follows persisted eligible candles; exchange-holiday labels require an explicit calendar.");
  if (confounded) limitations.push("Multiple related news events overlap the event window."); if (gap) limitations.push("The candle series contains gaps."); if (stale) limitations.push("One or more candles are stale."); if (receivedAt !== publishedAt) limitations.push("Availability uses the later of publishedAt and receivedAt.");
  const windows = params.postEventWindowsMin.map((windowMin) => {
    const selected = selectPrices(series, availableAtMs, params.preEventWindowMin * 60_000, windowMin * 60_000, asOfMs); const rawReturn = selected.before && selected.after ? returnOf(Number(selected.before.close), Number(selected.after.close)) : null; let benchmarkReturn = null; let benchmarkUnavailable = true; let benchmarkBefore = null; let benchmarkAfter = null;
    const benchmarkCompatible = benchmarkInstrument && benchmarkInstrument.verificationStatus === "verified" && benchmarkInstrument.currency === instrument.currency && benchmarkInstrument.sessionPolicy === instrument.sessionPolicy;
    if (benchmarkCompatible) { const benchmarkSeries = compatibleSeries(benchmarkCandles, benchmarkInstrument, params.interval, params.adjustmentMode).filter((candle) => Date.parse(candle.closeTime) <= asOfMs); const benchmarkSelected = selectPrices(benchmarkSeries, availableAtMs, params.preEventWindowMin * 60_000, windowMin * 60_000, asOfMs); benchmarkBefore = benchmarkSelected.before; benchmarkAfter = benchmarkSelected.after; benchmarkReturn = benchmarkBefore && benchmarkAfter ? returnOf(Number(benchmarkBefore.close), Number(benchmarkAfter.close)) : null; benchmarkUnavailable = benchmarkReturn == null; }
    const abnormalReturn = rawReturn != null && benchmarkReturn != null ? rawReturn - benchmarkReturn : null; const fields = [selected.before, selected.after, rawReturn].filter((value) => value != null).length; const coverage = fields / 3; const windowLimitations = [...limitations]; if (!selected.before || !selected.after) windowLimitations.push("Insufficient eligible closed candles for this window."); if (benchmarkUnavailable) windowLimitations.push("Benchmark unavailable; raw return only.");
    return { windowMin, priceBefore: selected.before?.close ?? null, priceBeforeAt: selected.before?.closeTime || null, priceAfter: selected.after?.close ?? null, priceAfterAt: selected.after?.closeTime || null, rawReturn, benchmarkInstrumentId: benchmarkInstrument?.instrumentId || null, benchmarkReturn, benchmarkUnavailable, abnormalReturn, relativeVolume: relativeVolume(series, selected.before, selected.after, params.relativeVolumeLookback), dataCoverage: coverage, confidenceMethod: confidence({ coverage, confounded, gap, stale }), limitations: [...new Set(windowLimitations)], provenance: provenance(news, selected.before, selected.after, benchmarkBefore, benchmarkAfter) };
  });
  const sufficient = windows.some((window) => window.rawReturn != null); return { methodVersion: NEWS_PRICE_COUPLING_V2, methodLabel: "Movimiento asociado temporalmente; correlación, no causalidad.", newsId: news.id, instrumentId: instrument.instrumentId, publishedAt, receivedAt, availableAt: new Date(availableAtMs).toISOString(), preEventWindowMin: params.preEventWindowMin, postEventWindowsMin: params.postEventWindowsMin, marketSession: resolveEventMarketSession(instrument, new Date(availableAtMs)), competingEvents: competitors, confounded, dataQuality: !sufficient ? "insufficient_data" : stale ? "stale" : gap ? "gaps_detected" : "observed", calculatedAt: asOfIso, windows };
}
